name = "EliminateGraphs"
uuid = "b3ff564c-d3b6-11e9-0ef2-9b4ae9f9cbe1"
authors = ["JinGuo Liu", "WenJie Peng"]
version = "0.2.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
Combinatorics = "1.0.2"
Graphs = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
